### PR TITLE
Promo Material for September Meetup

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by vStone** [comment]
Perhaps leave the binary blobs out and only add a 'template' svg?

**Comment by roidelapluie** [comment]
The svg will look like ugly if you do not thave the right fonts, that i why I wanted to add the binary. What we can do is just let this PR open and I will remove the binary after the conf has passed (then no promo will be needed)

**Comment by vStone** [comment]
You can export text to paths :) No font needed in the svg then. If the license of the font allows it, you can also add it to the repo for future use.

**Comment by roidelapluie** [comment]
What do you expect from me? :)

I have of course used open source fonts: Roboto from Google (Apache-2.0) and Font Awesome (MIT). I will change this PR.

**Comment by roidelapluie** [comment]
@vStone I have addressed your comments, care to merge?

**Comment by vStone** [comment]
Looks like there is still an image embedded. I'd rather have that external ;-)

**Comment by roidelapluie** [comment]
@vStone done :)

**Pull request merged**
